skatejs/skatejs

- src/skate.js
There was inconsistent behaviour when this occurred in the <head> script tag, due to the debounce providing a timeout.
This caused problems in IE (sometimes execution was slow enough that by the time the timeout was complete, the DOM was still not ready.)
> Wait for DOM ready before initialising pre existing elements

- src/skate.js
> Don't share the same object literal for prototypes when unspecified (#122)

- src/skate.js
> Default extends prop (empty str) is not a valid tag name (#119).

- src/lifecycle.js
- src/mutation-observer.js
- test/unit/attributes.js
- test/unit/init.js
- test/unit/registration.js
- test/unit/registry.js
- test/unit/version.js
Fixes #154.
There are currently still failures across all three browsers due to timeouts before the `done()` callback is called in the tests:
```text
IE 11.0.0 (Windows 7) DOM General DOM node interaction. should pick up descendants that are detached if an ancestor's innerHTML is set. FAILED
timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
IE 10.0.0 (Windows 7) DOM General DOM node interaction. should pick up descendants that are detached if an ancestor's innerHTML is set. FAILED
timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
IE 9.0.0 (Windows 7) DOM General DOM node interaction. should pick up descendants that are detached if an ancestor's innerHTML is set. FAILED
timeout of 2000ms exceeded. Ensure the done() …
```
> Fix failing tests in IE9, 10, and 11

- src/lifecycle/created.js
- test/unit/init.js
Fixes #179.
Also fixes tests in browsers that support native custom elements by checking if we should apply the prototype at runtime in a different way.
> Move triggering of attribute created callbacks to after the created lifecycle callback is triggered.

- src/api/type.js
- src/constants.js
- src/defaults.js
- src/index.js
- src/polyfill/binding.js
- src/polyfill/element-constructor.js
- src/polyfill/registry.js
- src/util/ignored.js
- test/perf/inserting-elements.js
- test/unit/api/init.js
- test/unit/registry.js
The idea behind this is that it gives us the ability to pull out unnecessary binding types at a later point. I think it's really worth considering only having the w3c compat spec as the only binding type by default but have the ability to add in custom ones. This way we could remove legacy support for older components as we see fit without affecting backward compatibility in Skate after 1.0.
Some things addressed as part of this:
- Added perf tests for different number of mutation observers on the page and their impact on performance.
- Removed constants file as it's not necessary.
> Modularise binding types

- README.md
[jspm](https://github.com/jspm) seems like the way forward for ES6 package management, so I've added an example for installing skate using jspm in the readme, which is similar to npm's example but requires the `npm:` prefix, which could potentially trip up newcomers.
> add example for installing with jspm

- test/unit/dom.js
Tests are currently failing but should be fixed by #259.
Implements #272, references #259
> Write tests to ensure tagName and childNodes don't throw errors.

- src/lifecycle.js
- src/registry.js
skate.js will fail to resolve `element.tagName` and `element.childNodes` in rare cases when processing `object` tag that is used to expose NPAPI plugin inteface to js.
> Bugfix for <object> tag edge case usage

- docs/src/docs/index.html
- docs/src/index.html
I synced up the benefits on the front page with the benefits listed on the issue and on the docs subpage. In doing so I've had to remove some of the other benefits that were on the front page  like browser compatibility. Let me know if you think these are still important to put on the front page or we can find somewhere else to put them too.
Main thinking behind this is to make sure the docs and front page are in sync, it's better to have a consistent message across pages IMO.
> #260 - changing wording of tag line and sync benefits between docs and frontpage

- src/lifecycle.js
- src/mutation-observer.js
Found today problem with rendering simple DOM tree in browsers that doesn't support custom-elements natively (all except Google Chrome).
DOM tree example
```xml
<component1>
<section class="some-class"></section>
<section class="some-class2">
<component2 id="id1">
<content>
Some content
</content>
</component2>
<span></span>
<component2 id="id2">
<content>
Some content
</content>
</component2>
<span></span>
<component2 id="id3">
<content>
Some content
</content>
</component2>
</section>
</component1>
```
Last `<component2>` node that was not initialized after appending to document. Problem was with `MutationObserver` shim that was not firing event on appending child nodes to `section.some-class2`.
I was trying to recreate issue in tests with simple DOM manipulations but with no luck. …
> Fixed rare issue with components initialization

- bower.json
This fixes:
`bower invalid-meta  skatejs is missing "ignore" entry in bower.json`
and also prevents downloading unnecessary files & folders
> Fix missing ignore section in bower.json

- src/utils.js
- test/unit.js
- test/unit/utils.js
PR that pulls in fix from #306 and updates the check in the `while` loop. Added test to ensure `getClosestIngoreElement()` works for elements in an iframe.
> #306 - Make getClosestIgnoredElement iFrame-safe

- src/index.js
- src/lifecycle/created.js
- test/unit/registration.js
This fixes an issue where skating an element more than once would fail to update the prototype after the first time. This happened because the check for `isNative` just checked for the presence of `createdCallback` on the element, which would be set the first time the element was skated.
The solution is to store the result of the first check for `isNative` and use that value instead.
> Fix overriding prototypes

- src/index.js
It looks like passing `isNative` as an option to `document.registerElement` was causing weird behaviour (in only some cases).
The solution in this PR is to only store `isNative` in `opts` if the element is non-native.
Fixes #325
> Only store isNative on opts if it is not native

- src/lifecycle/properties.js
- test/unit/lifecycle/properties.js
Make a deep copy of the properties object before modifying it, to prevent leakage from modifications to the object
> Fix leaking property init val

- src/api/init.js
- src/index.js
- src/lifecycle/attached.js
- src/lifecycle/attribute.js
- src/lifecycle/created.js
- src/lifecycle/detached.js
- src/lifecycle/events.js
- src/lifecycle/properties.js
- src/lifecycle/render.js
- test/unit/api/init.js
- test/unit/attributes.js
- test/unit/extending.js
- test/unit/lifecycle.js
- test/unit/lifecycle/created.js
- test/unit/lifecycle/events.js
- test/unit/lifecycle/properties.js
- test/unit/lifecycle/ready.js
- test/unit/lifecycle/render.js
This implements #335. Changes:
- All functions *not* on the prototype now receive an argument which is the element instead of using `this`. The function is always the first argument.
- The `attribute` callback now receives an object literal as its second argument that contains what was previously the `name`, `newValue` and `oldValue` arguments. This does not conform to native custom elements, however, it's a better design choice for an API because you do not have to remember argument ordering, only names.
- The `properties` callback `update()` now follows the same convention as the `attribute` callback.
> #335 - Go back to using an argument instead of 'this'

- src/lifecycle/events.js
- test/unit/lifecycle/events.js
> #302 - Make currentTarget and delegateTarget consistent with jQuery event objects.

- package.json
Fixes:
```console
npm WARN package.json skatejs@X.X.X No license field.
```
> chore: fix npm license field

- test/unit.js
- test/unit/mutation-observer.js
This adds a simple test for the MutationObserver - in preparation for automated tests on IE
> test: Add test for MutationObserver polyfill

- build/task/test.js
Broke watching when backporting saucelabs from master
> chore: fix singleRun

- src/document-observer.js
- src/lifecycle.js
- src/mutation-observer.js
- test/lib/polyfills.js
- test/unit/lifecycle.js
- test/unit/mutation-observer.js
This fixes the lifecycle management on IE (e.g. incorrect calls to `fallback` instead of `created` and `removed`).
> Fix mutation observer / lifecycle management on IE

- build/task/build-test.js
- package.json
- test/boot.js
This adds the webcomponents.js MutationObserver polyfill to skate in order to get some tests for older browsers green.
> chore: use webcomponents.js MutationObserver polyfill

- build/task/test-watch.js
- build/task/test.js
simplifies the tasks and enables proper watching (no browser restarts), which also allows you to attach external browsers (let's say an IE in a VirtualBox :tada:)
> chore(test): fix proper watching

- build/lib/saucelabs-launchers.js
This adds Opera as a browser for our saucelabs tests
> chore(test): add Opera for saucelabs

- build/lib/saucelabs-launchers.js
This adds Safari 8 to the list of our saucelabs-tested browsers
> chore(test): add Safari 8 to saucelabs-tested browsers

- src/fix/ie/innerhtml.js
This fix makes sure that the `innerHTML` fixes regarding `DOMNodeRemoved` delegation only get applied once. This is important if we run multiple skate versions on one page.
> fix(IE innerHTML): only enhance once

- src/support/valid-custom-element.js
Implements http://www.w3.org/TR/custom-elements/#dfn-custom-element-type, namely:
- all characters must be lowercase
- name must not be one of
- 'annotation-xml',
- 'color-profile',
- 'font-face',
- 'font-face-src',
- 'font-face-uri',
- 'font-face-format',
- 'font-face-name',
- 'missing-glyph'
> Add stricter checks for element names

- package.json
- src/api/properties/boolean.js
- src/api/properties/float.js
- src/api/properties/index.js
- src/api/properties/number.js
- src/api/properties/string.js
- test/unit/api/properties.js
- test/unit/index.js
Also allows typed properties to have an `undefined` value.
> #433 - Use property functions instead of objects.

- src/defaults.js
My first code-contribution to skate.
The missing default is actually preventing copying over `render` from user options when they are passed as ES6 class.
Another thing I noticed is that options are treated as enumerable but they can also be a class which is not enumerable. I only fixed the defaults here. Issue should be opened for the enumerable problem.
> Missing default of `render` 

- README.md
Add a short section to document the `detail` option for `eventOptions` in `skate.emit`
> Document the 'detail' option for skate.emit

- README.md
- package.json
- src/api/create.js
- src/api/init.js
- src/api/ready.js
- src/api/render.js
- src/index.js
- src/shared/document-observer.js
- src/shared/registry.js
- src/type/element.js
- test/unit/api/fragment.js
- test/unit/api/init.js
- test/unit/constructor.js
- test/unit/dom.js
- test/unit/lifecycle.js
- test/unit/registration.js
- test/unit/registry.js
We use to allow multiple component bindings. This brings it closer to the spec, lessens ambiguity and improves performance.
For those that want multiple bindings, create a component that applies several bindings, or write your own binding type.
> #475 - only one element may be upgraded with a single component's behaviour

- src/api/ready.js
- src/lifecycle/attached.js
- src/lifecycle/created.js
- src/lifecycle/detached.js
- test/unit/api/ready.js
Also removed spots that didn't need to use a data namespace.
Results:
44,758 -> 169,962 ops/sec (Chrome) and 146,570 opts/sec (Firefox)
This is compared to 314,351 ops/sec for the native custom element implementation (Chrome) and 89,190 ops/sec for the custom element polyfill (Firefox).
Breaking changes are that this only now calls the callback for component elements. It used to fire for any element by checking to see if it had a component definition. However this causes problems because you may not have registered the element yet and don't want the callback to fire until you do. You can't have both. It also simplifies the behaviour of this function and you should only be passing in component elements anyways.
> #479 - Fix performance issues with skate.ready()

- .travis.yml
as we got rid of all direct bower dependencies, the `bower` install step is not needed any more in the travis build.
> chore(bower): remove install step from build

- package.json
* removed Chrome 43, because `constructor should be accessible` was failing for some strange reason
* removed Opera 11 because it couldn't deal with `.stopImmediatePropagation`
closes #457.
> chore: add more saucelabs browsers

- package.json
- src/global/vars.js
This fixes #493 for 0.14.x
refs #494 #495 
@treshugart @jpnelson @seancurtis PTAL
> fix(globals): do not share globals between skate versions

- lib/lifecycle.js
- src/lifecycle.js
- src/mutation-observer.js
- test/unit/attributes.js
- just Edge. Chrome, IE, FF all fine.
- Plus a hacky lifecycle fix for AUI but still need to fix failing test
The new test is the only one that fails on Edge - it describes an existing element with an existing attribute. I may be missing something in the skate definition but the failing test is consistent with the failing tests i'm seeing in AUI 5.9.x which is based on the same 0.13.x skate branch (but please let me know the definition needs extra config)
> Edge existing attr mutation poc

- README.md
Babel gave error on this, apology if that some new javascript syntax though... like ES2222 no colons in object declarations :P
> Readme example added missed colon

- src/api/version.js
- src/index.js
- test/unit.js
- test/unit/index.js
- test/unit/version.js
The build doesn't bump this anymore and it doesn't make sense when consumed via a package manager
because it's in the package manifest already. It only makes sense in a global world which is quickly
going away.
BREAKING CHANGE: remove version module #619
> #619 - Remove version module and tests.

- src/api/vdom.js
- test/unit/vdom/elements.js
> #654 - Fix vdom.element() when passing a string as the second argument

- README.md
- src/api/define.js
- test/unit.js
- test/unit/api/define.js
- test/unit/registration.js
If a component with the same name has already been registered, Skate will use the specified name as  a prefix and append a number to the name before registering it.
Fixes #564 and implements #663.
> #564, #663 - Multiple components with the same name

- src/util/support.js
- test/unit/util/support.js
Changed to the `Function.prototype` in `nativeProperty`, since webcomponents shadowDOM polyfill polyfillng everything and old approach didn't work as expected.
`shouldUseShadowDomV0` and `shouldUseShadowDomV1 ` became simpler.
> fix: fixed native polyfill detection

- src/api/vdom.js
- test/unit/vdom/incremental-dom.js
Fixes #679.
Something that we're not doing yet is passing `key` and `statics` on to helpers. This would increase the number of arguments, else we can create a generic object to pass in to the helper instead. Currently the API shape looks like:
```js
const Helper = (props, chren) => {};
```
With `key` and `statics` added:
```js
const Helper = (props, chren, key, statics) => {};
```
We could combine them:
```js
const Helper = (props, chren, { key, statics }) => {};
```
Pass them as `props`:
```js
const Helper = ({ key, statics, ...props }, chren) => {};
```
Or do everything together:
```js
const Helper = ({ key, statics, props, children }) => {};
```
> #679 - Fix props being passed to function helpers when calling Incremental DOM directly

- src/api/vdom.js
- test/unit/vdom/events.js
BREAKING CHANGE: ontest no longer works. Implements #694.
> feat(events): Support onTest and on-test.

- src/api/component.js
- test/unit/lifecycle/attribute-changed.js
According to the documentation, `The attributeChangedCallback() is invoked for every attribute that exists on the element at the time of creation.`.
But for the properties that were defined as attributes this callback was never called.
This PR is fixing it.
> fix: attributeChanged fixed

- README.md
- package.json
- src/api/vdom.js
- test/unit.js
- test/unit/vdom/ref.js
- test/unit/vdom/skip.js
Fixes #721 and #724.
Some minor refactors to simplify the default attribute handler.
Fixed `ref` so that it will only be called if the element changes or if the ref changes. if you specify a closure in `render()` it will always change. If you supply a function that doesn't change, it will only ever be called if the element is re-rendered.
Fixed `skip` so that it actually skips the entire tree. Incremental DOM requires that you either `skip()` or render your tree. Providing this API is syntactic sugar for not having to worry about `if / else` blocks and makes it more declarative. This is being provided as a fix as it was originally intended to work this way, but was broken.
See this [bin](http://jsbin.com/yaralol/12/edit) for how you'd do it with IDOM.
> #721 - Fix ref

- src/api/emit.js
- test/unit/api/emit.js
Firefox still has a bug regarding this issue. This also fixes a problem where we couldn't emit
events on any elements (custom elements) that have a "disabled" property and this is absolutely
something that people need to do.
Fixes #726.
> fix(emit): Fix emit behaviour so that it's consistent with all browsers.

- src/api/define.js
- test/unit/api/define.js
When there are multiple skate instances on a page, some components could be defined in more than one instance. This PR ensures that even in this situation all the components will be registered.
> fix: define for multiple instances

- src/lifecycle/props-init.js
- test/unit/lifecycle/properties.js
Setting a property to the same value twice and then trying to set the linked attribute will not update the property in native (Chrome + Chrome Canary).
This is because the second time the property setter is run, trying to set the linked attribute to the same value won't trigger the `attributeChangedCallback` callback.
> Fix linked attribute going out of sync

- src/lifecycle/props-init.js
- test/unit/lifecycle/properties.js
Followup to the fix for #733, check that the actual attribute value has changed after serialization
Fixes #738
---
The issue was that we were only checking that value had changed, not that the attribute value had changed (which was the root cause of the problem). We need to check that the new attribute value (i.e. `serializedValue`) is not new.
Also moved tests to a new section at the bottom of the file, and added one new test.
> fix: Fix for setting a linked attribute not updating the property

- src/api/vdom.js
- test/unit/vdom/ref.js
- test/unit/vdom/skip.js
> fix: skip and ref behaviour for vdom.elementVoid

- src/api/vdom.js
- test/unit/vdom/properties.js
> fix: Apply skate semantics to element attributes in a stack context.

- README.md
- package.json
- src/api/component.js
- src/api/prop.js
- test/unit.js
- test/unit/api/properties.js
- test/unit/extending.js
WIP: 
Still retains support for native and the webcomponents.js v1 polyfill. Adds support for IE 9 and 10 mostly through just consuming the `document-register-element1` polyfill.
> #742 - add support for webreflection/document-register-element

- src/api/emit.js
- test/unit/vdom/events.js
This fails for Chrome (53.0.2785), passes for Firefox (48.0.0), so needs a fix to move forward.
**DO NOT MERGE** if you want a green build. :)
> Fix case where event is not emitted outside of the shadow dom in Chrome 53 (native v1 shadow dom)

- README.md
Ok. So I didn't have a nice commit message for semantic release. See #774
This resolves that, and also adds some basic docs about the compose flag.
> fix: Allow events to bubble by default out of the shadow dom in native v1.

- src/lifecycle/props-init.js
- test/lib/support.js
- test/unit/lifecycle/properties.js
This fixes the test CI by skipping a few tests in IE9 and 10.
> fix: skip ES2015 class tests that rely on statics inheritance in IE9 and 10

- src/api/component.js
- src/lifecycle/props-init.js
- src/util/get-prop-data.js
- src/util/sync-prop-to-attr.js
- test/lib/has-symbol.js
- test/unit/api/props-with-symbol.js
- test/unit/api/props.js
Use the prop names as keys instead of prefixing with a string, so that skate can differentiate between multiple symbol props. Previously, using two Symbols with the same descriptor would generate something like:
```
{ 
'api/property/Symbol()': { ... }
}
```
since we were just converting the Symbol to a string.
Also, put the props inside an object with key `props` to prevent clashing with any other skate data.
> Fix multiple symbol props

- src/api/component.js
- src/api/props.js
- src/util/debounce.js
- test/unit/api/props.js
- test/unit/lifecycle/render.js
- test/unit/vdom/elements.js
- test/unit/vdom/events.js
- test/unit/vdom/incremental-dom.js
- test/unit/vdom/properties.js
- test/unit/vdom/ref.js
- test/unit/vdom/skip.js
Copying across @zzarcon's [concern](https://github.com/skatejs/skatejs/pull/850#issuecomment-252840327):
> This approach seems quite good to me, the only thing Im wondering its if we should disconnect the `MutationObserver` observer when the component gets disconnected? 
> Not sure if right now we will leak something, or maybe we just don't need to care about it.
> Use microtasks for debounce scheduling if available, resolves #846.

- package.json
The pre-commit hook failed every single commit even if re-npm installing. It also adds jshint files and unnecessarily modifies the package.json on every fresh install.
This will make its way back in to skatejs-build in another form.
> chore: Remove pre-commit hooks and cleanup unnecessary npm scripts.

- src/util/debounce.js
- src/util/native.js
- test/unit/util/debounce.js
- test/unit/util/native.js
native MutationObserver feature detection was incorrect for mobile safari 9.0 . Also, microtasks
were not debounced correctly
> fix(util): fix mobile safari 9.0 - mo + microtask debounce

- README.md
- src/api/component.js
- src/api/define.js
- src/api/symbols.js
- src/api/vdom.js
- src/util/support.js
- src/util/symbols.js
- test/boot.js
- test/unit/api/define.js
- test/unit/index.js
- test/unit/vdom/elements.js
- test/unit/vdom/events.js
- test/unit/vdom/properties.js
- test/unit/vdom/shadow-dom.js
- test/unit/vdom/skip.js
Fixes #710.
Since v1 is support in Chrome, there's no need to support v0 even if Opera hasn't updated yet. Until they pick up the new Blink (if they haven't already) people wanting to support opera can use the polyfills.
> #710 - remove support for v0

- package.json
- src/index.d.ts
This aims to resolve the TypeScript portion of #754, by introducing a first-stab at definitions.
> fix: Add TypeScript definitions.

- README.md
- src/api/component.js
- src/api/prop.js
- src/api/props.js
- src/lifecycle/props-init.js
- src/util/get-default-value.js
- src/util/get-initial-value.js
- src/util/get-props-map.js
- src/util/object-is.js
- src/util/prop-definition.js
- src/util/sync-prop-to-attr.js
- test/unit/api/properties.js
- test/unit/lifecycle/properties.js
With the new internal class 'PropDefinition' I have simplified a few functions.
@treshugart @Hotell @bradleyayers this PR is now ready for you to review.
Besides a pure refactor there is a small change in how NaN works for a prop.number().
Setting the prop to NaN will maintain the NaN value and serialize attribute to 'NaN' which deserializes back to NaN.
This should be a small breaking change that will not affect most common usecases.
I had to only change one test and use Object.is for testing equality of NaN equal NaN.
There was also a bit of inconsistency in the code where empty was sometimes normalized to undefined and in other places to null. Now everywhere empty is normalized to null. This didn't affect any tests.
This should also be transparent to most users since each build-in prop …
> #957 - class PropDefinition holds prop name and normalized prop options

- package.json
- src/api/component.js
- src/api/define.js
- src/api/emit.js
- src/api/vdom.js
- src/util/debounce.js
- src/util/root.js
- webpack-blocks.js
Looks like the Webpack 2 refactor broke the global name for `incremental-dom` (`IncrementalDOM`). The `window-or-global` package also doesn't export a global it seems, so I just refactored that out and created a smaller util for it. @Hotell should be happy about that :p
> Fix global

- src/index.d.ts
- src/jsx.d.ts
- src/ts-typings/api.d.ts
- src/ts-typings/common.d.ts
- src/ts-typings/jsx.d.ts
- test/definitions/misc.tsx
- test/definitions/sample-component.tsx
- tsconfig.json
Closes #1010 
- also adds proper type checking and intelisense for Stateless Components 🍺 
TODO:
> fix(ts-typings): update ts typings

- src/ts-typings/api.d.ts
- src/ts-typings/common.d.ts
- test/definitions/misc.tsx
What this PR does:
- as discussed within #1020 SFC don't support ref and slot by default. So this is addressed within this fix
- adds proper type annotations to `emit`
- adds proper type annotations to `props`
- adds missing `role` attribute
> fix(ts-typings): add proper emit,props defs and make SFC not allow ref and slot props by default 

- package.json
- src/api/emit.js
- test/boot.js
- test/unit/api/emit.js
- test/unit/vdom/events.js
- yarn.lock
It was originally inverse to the default behaviour to preserve backward compatibility when the spec
churned. Now that we can make breaking changes towards 5.0, we can make this behave as it should by default, for encapsulation purposes.
BREAKING CHANGE: fixes #768
> refactor(emit): Reverse behaviour of the composed flag.

- src/with-component.js
when the web component rerender after propertiies changes, the new node is appended to the shadow root but the old ones are not removed. (same result cross browser)
I don't know if it is the right fix but this one seems to work
> fix node refresh

- docs/recipes/design-patterns/component-composition.md
Add missing `http://` to link to the article "'Real' Mixins with JavaScript Classes"
> Correct link in documentation

- src/util/with-props.js
- test/unit/props.spec.js
fixes #1111 
Properties were defined at each instantiation of a given element. These caused the backing symbol to be changed for each instance but as the properties are defined on the prototype, this meant that all instances apart from the last actually lost track of the props value.
This was visible in usage when instantiating the same component multiple times in a page at the same time (with innerHTML for example). Only the last one actually got access to the props when render time comes (after debounce).
> Fixed multiple definition of properties on the same constructor.

- src/with-component.js
- src/with-render.js
- test/unit/with-render.spec.js
The goal of this is to make the renderer API as simple as possible, but also as extensible as possible for consumers when extending `withRender()`. Edge cases can just extend `withProps()` and use `propsUpdatedCallback()`.
> 1. Streamline render

- src/with-component.js
- src/with-props.js
- src/with-render.js
- test/unit/with-render.spec.js
This fixes #1134.
When properties change, the renderer function is called. This is done by implementing propsChangedCallback within with-render.
Also fixes an issue where any renders after the first would not result in the shadowRoot being updated, because we weren't passing the preact component back into preact's `render` method.
> Call renderer when props change

- package.json
Yarn complains if a package doesn't have a version field, even when pulled from GitHub. This adds one.
> Add version field to package.json

- src/with-render.js
- test/unit/with-render.spec.js
This ensures that we do not throw on the first render if the element already has a shadow DOM (such as if the element creates its own shadow in the constructor).
Closes #1140
> Allow elements to create their own shadow

- nwb.config.js
- package.json
- yarn.lock
The `lib/` build was putting stuff directly on `exports` (which is fine for CJS). However, this caused issues when loading from unpkg like we've been able to do before becuase it used to piont to `umd/` which put stuff onto a `skate` global (and is also loadable from CJS and AMD).
> #1150 - fix "main" issue from pointing it to "lib/"

- src/emit.js
- src/util/index.js
- src/util/with-props.js
We either have to use `Object` from the global, or explicitly export it as a util and import it from that. The latter is probably better just in case it's overridden in a containing scope.
> #1151 - fix Object errors

- src/emit.js
There seems to be a problem with skatejs.emit when an emitting component is part of the shadowDOM template of another component specifically in Chrome; The event never bubbles out of the shadowDOM even with the use of {composed: true}. 
Test Case (using TypeScript): 
```JS
import { Component, h, emit } from 'skatejs';
export class Wrapper extends Component<void> {
static get is() { return 'el-wrapper'; }
constructor() {
super();
// Never reached :(
this.addEventListener('internal-event', (event) => console.log('Event received', event));
}
renderCallback(){
return (
<div><el-emitter></el-emitter></div>
);
}
}
customElements.define(Wrapper.is, Wrapper);
export class Emitter extends Component<void> {
static get is() { return 'el-emitter'; }
connectedCallback() {
super.connectedCallback(); …
```
> Use CustomEvent when available

- src/with-renderer.js
Refactors `withRender.renderRoot` getter method to avoid reassigning `_shadowRoot` property each time is called and remove redundant line.
> refactor(render): Simplify withRender.renderRoot getter implementation

- src/with-props.js
- test/unit/with-props.spec.js
If you created a base class and based several components off of it, it would contain *all* of the props for every component deriving from it. This doesn't normally happen because mixins create new classes, but it shows up if you reuse a base class.
> Fix shared props

- src/util/with-props.js
- test/unit/with-props.spec.js
**Please check if the PR fulfills these requirements**
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```
Fixes a bug where you can't use symbols as name of props if using the props helpers.
I'm not sure if this is the right approach, since I'm not entirely sure of the side effects of not having a dashCased string name.
> fix: Symbol named props

- .github/PULL_REQUEST_TEMPLATE.md
**Please check if the PR fulfills these requirements**
Just noticed the pull request template has a dead url, not sure if should be pointing to 5.x or master, but its currently broken
> docs: Update commit message url

- CONTRIBUTING.md
- README.md
- site/components/_.js
- site/index.js
- site/utils/load-sample.js
- test/samples/simple/index.html.js
- test/samples/simple/index.js
- test/samples/simple/index.result.js
- test/samples/simple/index.spec.js
- test/samples/with-preact/index.js
- test/samples/with-preact/index.spec.js
#860, #903 
This is an attempt at demonstrating a few ways in which Skate can be utilised in the README, going from "simple" through to "complex", and making the "site" code orthogonal to it at the same time.
The two primary challenges with the docs are (1) the flow, and (2) their simplicity.
1. It's challenging to construct a linear flow through what Skate "is" and incremental examples of web components authored via Skate. The difficulty lies in requisite knowledge (i.e., what can we expect people to know prior to looking at Skate) and relevance (i.e., when people want to author web components, what will pique their interest the most?). This leads in to the second problem...
2. Simple examples of using Skate aren't that "simple" -- by that, I mean they end up looking less terse than I'd …
> Doc changes

- src/index.js
- src/with-component.js
- src/with-props.js
- src/with-renderer.js
- src/with-state.js
- test/unit/index.spec.js
- test/unit/with-props.spec.js
- test/unit/with-state.spec.js
#1237
This implements state using a separate mixin. The mixin has a getter and setter that calls `triggerUpdate` if it's defined on the instance.
The tests test both setting and that `triggerUpdate` is called. All other functionality is assumed ot be borrowed from something like `withProps` that implements a `triggerUpdate` method.
Theres some other stuff here:
- Moved the `_connected` check to `withRender`. No use in doing this in the props mixin unless we really want to block any props reactions when not connected. We should be doing this check in `withRender` anyways even if it's done in props.
- Added tests to `withProps` to ensure `triggerUpdate` and `triggerUpdateBatched` are called.
- Should we mix this in with `withProps`? I feel like too many mixins are going to get us into perf …
> #1237 - Implement state

- README.md
Update readme to:
* fix typos
* fix broken installing link
* fix template string expression in custom mixin example
* update possible values of [renderer] to the correct ones
> Fix typos and broken link in readme

- packages/renderer-lit-html/README.md
- site/pages/renderers/with-lit-html.js
I ran into the problem of attributes no longer rendering when migrating from direct usage of `lit-html`'s `render` in `connectedCallback` to `withLitHtml`. This lead me to realizing that the `withLitHtml` uses the extended render from `lit-html`. I was surprised since the extended renderer's exist isn't really loudly documented by `lit-html`'s readme. This change points to the extended renderer's docs and hopefully prevents others from going on the debugging journey I went on.
I wasn't sure if it made sense to update both the readme and the site but I did both in case that's what you'd want.
It's possible it makes more sense to link to the file within lit-html's repo and not a specific line since that …
> Clarify lit html renderer

- packages/renderer-react/package.json
Allows React 16 to be used without warnings
> chore(react): Updates peerDependencies to allow React 16

- packages/renderer-react/src/__tests__/__snapshots__/index.js.snap
- packages/renderer-react/src/__tests__/index.js
- packages/renderer-react/src/index.js
Per [this twitter thread](https://twitter.com/BedeOverend/status/941975889348214785), this PR explores wrapping React components via a separate function exported with `renderer-react`.
Instead of:
```js
import ReactComponent from 'a-react-component';
import withReact from '@skatejs/renderer-react';
export default class extends withReact() {
static component = ReactComponent
}
```
usage would be:
```js
import ReactComponent from 'a-react-component';
import { asCustomElement } from '@skatejs/renderer-react';
export default asCustomElement(ReactComponent);
```
Currently it doesn't (as this PR just moves from static to an external function), but might be worth having `asCustomElement` export a fully fledged CustomElement that'll mimic the React component's lifecycle methods. I'm guessing for …
> renderer-react: wrap via asCustomElement

- site/pages/renderers/__samples__/wrap-react.html
- site/pages/renderers/__samples__/wrap-react.js
- site/pages/renderers/with-react.js
Adds documentation about the `wrap` function - it's pretty minimal, just showing that it exists and a _very_ basic example.
cc @treshugart
> Add to with-react renderer showing wrap usage. Fixes #1281

- package.json
- packages/ssr/jest.js
- packages/ssr/package.json
- packages/ssr/register/Node.js
- packages/ssr/test/Node.test.js
- yarn.lock
This PR does a few things let me know if you'd like me to break it up.
- Firstly this enables usage of either jest 21 or jest 22. This required an update to the `jest-environment-node` dep as well as working around a [breaking change](https://github.com/facebook/jest/blob/master/CHANGELOG.md#features-3).
- Secondly this adds a thin `cloneNode` implementation. This implementation *should* be sufficient for 99% of cases. I'm sure there are some edge cases where the duplication won't be sufficient however I don't know what those might be without doing more serious testing.
- Thirdly this fixes a bug with `.content` which was causing it to return an incomplete `documentFragment`. This is because …
> Ssr improvements

- packages/skatejs/src/with-renderer.js
`undefined` appears in the DOM if the element doesn't render anything (f.e. the call to `() => this.render && this.render(this)` in the `updated` method returns `undefined` when there's no `render` method).
_Why have you implemented it this way? Did you try any other methods?_
The `||` check replaces the `undefined` with an empty string.
_Are there any open questions about this implementation that need answers?_
_List any tasks you need to do here, if any. Delete this section if you don't
need it._
> Fix "undefined" appearing in the DOM if component doesn't render anything

- site/pages/mixins/with-renderer.js
This is just a doc update.
I added this because it may not be obvious, and people likely want to work with props and state before the new DOM is rendered.
Thoughts on this?
> tip about when to call super.updated

- packages/renderer-preact/src/index.js
Preact Renderer does not work in IE11.
`children` is not supported in IE11, falling back to `childNodes` instead.
> IE11 fix for preact renderer

- packages/renderer-preact/src/index.js
See https://github.com/skatejs/skatejs/pull/1432#discussion_r183381359
Makes unmounting Preact components simpler.
_Why have you implemented it this way? Did you try any other methods?_
Locally, I also downgraded `preact` to 8.2.5, the lowest supported version as specified in the Preact renderer's `peerDependencies`, and this change still worked, so I think we should be safe :)
> Simplify unmounting Preact components.

- packages/ssr/register/Node.js
- packages/ssr/test/Node.test.js
When a html node already has content (child nodes), textContent is appending the text instead of replacing
It removes the child nodes before adding the new one
> ssr: fix setting textContent when node has child nodes

- package.json
Globally installed package versions will vary. Unless version ^0.19.0 is required, this PR relaxes the mandatory range to 0.18.0 <= x <= 0.21.0. This allows for the use of the current version of bolt (0.20.7)
* [ :-1: ] Bug
* [ :+1: ] Feature
* [:+1:] Read the [contribution guidelines](https://github.com/skatejs/skatejs/blob/5.x/CONTRIBUTING.md).
* [ :-1: ] Wrote tests. 
Manually tested: 
* `npm install -g bolt@^0.18.0`, `bolt`, and `npm test` (0.18.4)
* `npm install -g bolt@^0.19.0`, `bolt`, and `npm test` (0.19.3)
* `npm install -g bolt@^0.20.0`, `bolt`, and `npm test` (0.20.7)
* [ :+1: ] Updated docs and upgrade instructions, if necessary.
Not necessary, but nice to support a range of clients if they all work.
Read some chatter about bolt becoming a package level dependency rather than …
> Allow for a range of recent bolt cli clients

- packages/renderer-preact/src/__tests__/component-as-name.js
- packages/renderer-preact/src/index.js
A new component was being defined every time a component constructor was rendered
Set preactNodeName prop to the actual constructor and not the descendant
Renamed test components to more descriptive names
> renderer-preact: fix caching of auto defined elements

- README.md
- packages/skatejs/src/with-update.js
- packages/skatejs/test/unit/with-update.spec.js
- site/pages/mixins/with-update.js
Currently is necessary to import props from skatejs package to define simple props types like string, number etc
Given the skatejs design based on mixins, most of the times, this is the only import from skatejs when defining a component class
By allowing to use native constructors like String, Number the props import could be avoided. It's also pretty intuitive and align with other libraries like [lit-element](https://github.com/Polymer/lit-element/)
With this change is possible to do
```
class Test extends MyComponent {
static props = {
str: String,
obj: Object
}
}
```
Used a Map instance to store the props definitions mapped to correspondent native constructor
Should props.any be mapped to null?
Should be added a function `registerPropType` to allow  sharing custom properties? 
To test …
> Allow to define prop type using native types constructors

- packages/sk-marked/src/__tests__/utils.spec.js
- packages/sk-marked/src/index.js
- packages/sk-marked/src/utils.js
Fixes #1457 
Previous implementation was stripping more than necessary
Its straight forward: check indentation of each line to detect baseline indentation. If no indentation is found break loop and dont strip lines
> sk-marked: fix baseline indentation stripping

- packages/skatejs/src/with-update.js
- packages/skatejs/test/unit/with-update.spec.js
Fixes spelling of normalize words. Notice that in some places already has the proper spelling
> Fix spelling of "normalize" words

- package.json
- packages/renderer-lit-html/package.json
- packages/renderer-lit-html/src/index.js
- site/package.json
- site/pages/renderers/with-lit-html.js
- yarn.lock
[lit-extended is deprecated](https://github.com/Polymer/lit-html/blob/master/src/lib/lit-extended.ts#L57) and does no longer support all the features it did before (e.g., on-click binding).
Replaced the render call from lit-extended with the call to the default render function. 
- This is a breaking change. The semver of the renderer-lit-HTML version needs to be bumped to a new major version. Should we change the version to a beta version as long as the lit-HTML dependency points to a dev version?
This is a breaking change. All lit-HTML component needs to be updated to use the new syntax.
> Use lit-html over the deprecated lit-html-extended

- .github/PULL_REQUEST_TEMPLATE.md
* [] Wrote tests.
* [] Updated docs and upgrade instructions, if necessary.
The link to the contribution guidelines in the PR template is broken.
> Fix the contribution guidelines link in pr template

- package.json
- yarn.lock
Use the babel-plugin-transform-builtin-classes in the es build to properly call the super constructor when extending HTMLElement.
Fixes #1465 
See #1465
Uses the [babel-plugin-transform-builtin-classes](https://github.com/WebReflection/babel-plugin-transform-builtin-classes/) to transform extends of built-in classes. The plugin only performs a static analysis to match base class names that might require the fix. Since skatejs use dynamic base classes it was needed to match the identifier `Base` that can potentially refer to a built-in class. 
I preferred the compilation step over using a library for inheritance since this is only needed when older browsers without class support are targeted. 
_Are there any open questions about this implementation that need answers?_
_List any tasks you …
> Fix extending builtin classes

- packages/ssr/register/ClassList.js
- packages/ssr/test/ClassList.test.js
Skate SSR's implementation of classList does not make mutations to the className, this PR fixed the issues and adds tests.
Fixes #1512
I didn't try anything else. I didn't feel the need to try and micro-optimize this implementation for obvious reasons.
What's going on with the deploy preview? It failed with `failed during stage 'building site': Deploy directory 'site/public' does not exist`. My changes should not have caused this.
All these questions make contributing painful.
> Fix classList mutation methods

- packages/core/src/props.ts
This is just a semantic change, as Array is a type of Object, but otherwise should behave the same. Not a big deal though.
> swap object with array in props

- package.json
That's all there is to it. (That's all I had to do in my projects, is update the version)
The lint-staged usage itself hasn't changed, but now we can do things like `git add -p` and selectively add changes, and only those changes will be formatted.
> update lint staged
