skatejs/skatejs

src/skate.js
=> Sync calls to createElement work natively by always registering

test/unit/components.js
=> Avoid error in tests when extending custom element by using span

package.json, test/lib/helpers.js, test/unit/attributes.js, test/unit/components.js, test/unit/dom.js, test/unit/events.js, test/unit/lifecycle.js, test/unit/registration.js, test/unit/templating.js
=> Unique tag names in tests to avoid re-registration errors (#120)

src/skate.js
See the commit message for 192a033 more details.
=> Native registerElement prototype must inherit from HTMLElement

src/defaults.js, src/index.js, test/polyfill/create-element.js
=> Remove defaults from the public API.

src/lifecycle/attribute.js, src/lifecycle/created.js, test/unit/attributes.js
=> Patch setAttribute / removeAttribute for synchronous attribute listener handling.

src/lifecycle/events.js, test/unit.js, test/unit/lifecycle/events.js
=> Implement ::shadow and /deep/ delegate support.

src/polyfill/mutation-observer.js, test/unit/api/watch.js
=> Correctly lookup mutation event target's parent node in polyfill

src/api/ready.js
=> Fix readyState handling in IE (since it was firing too early)

docs/templates/layout.html
The project is called Skate everywhere except the package name. Updating title of pages to match. 
Also, ignore my spelling skills it appears.
=> Updating template to fix #237

src/util/ready.js
=> Fix for ready callbacks being swallowed if readyState is interactive

src/skate.js
=> initDocument only inits after the document is ready (0.12.x)

src/lifecycle.js, test/unit/attributes.js
=> Check for camel cased version of attr before making property link

src/util/walk-tree.js
Check https://github.com/skatejs/skatejs/pull/292 for more info. Fix for #300
=> Fixed issue with componentes initialization described in #292

bower.json
=> fix bower ignore section

src/lifecycle/properties.js, test/unit/lifecycle/properties.js
=> Fix updating the property when setting a linked attribute

src/lifecycle/properties.js, test/unit/lifecycle/properties.js
=> Fix coerce initial prop val

package.json
:rocket:
One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.
You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.
Have a good day!
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>
=> Updated gulp-karma to version 0.0.5

package.json
:rocket:
gulp-debug just published version 2.1.1, so that’s now up to date in your `package.json`.
Check that it doesn’t break your code and release the new version of your software safe in the knowledge that it will stay in this working state.
---
This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.
<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>
=> Updated gulp-debug to version 2.1.1

CHANGELOG.md, README.md, src/api/fragment.js, src/api/render.js, src/index.js, src/lifecycle/created.js, src/lifecycle/renderer.js, src/util/create-from-html.js, test/unit.js, test/unit/api/fragment.js, test/unit/api/render.js, test/unit/index.js, test/unit/lifecycle/created.js, test/unit/util/create-from-html.js
=> #354 - Public API for rendering / re-rendering a component.

README.md
Looks like this was left over from before the readme was updated
=> pass element to created function example 

.travis.yml
=> chore: make travis run faster using container infrastructure

CHANGELOG.md, src/global/document-observer.js
Adds some information about our (old) polyfill and future direction.
=> docs: updates about MutationObserver

src/lifecycle/attribute.js
no need to create closure and process any attributes
=> perf: early exit in case we did not get a callback

test/unit/attributes.js, test/unit/lifecycle.js
This ports the lifecycle tests from 0.13.x to master
=> Add lifecycle tests

build/task/test.js, test/unit/attributes.js
This makes our PR tests fail for vital browsers (Chrome and Firefox for now). As soon as we had all our tests green for all supported browsers once, we should just generally fail for any failing browser.
=> Fail on vital browsers

src/api/property/boolean.js, test/unit/api/property.js
Fixes another IE test (seems as if IE allows setting actual `null` values to attributes)
=> Fix ie tests

build/lib/saucelabs-launchers.js
This enables IE edge on saucelabs
=> test: add IE edge to tested browsers

build/task/test.js, src/fix/ie/innerhtml.js, src/global/document-observer.js, src/global/ie/fix-innerhtml.js
=> fix: MutationObserver for IE11 and innerHTML fixes

.travis.yml, package.json
This fixes the performance tests and runs them automatically in our travis build.
=> fix(test): perf tests

build/task/test.js
This fails our build from now on if we introduce an error in one of the supported browsers.
=> chore: remove vital browsers and fail on all

build/task/test-watch.js, build/task/test.js, package.json
=> Add test watch

src/fix/ie/innerhtml.js
=> fix(IE innerHTML): only enhance once

bower.json
That way this project can be fetched by customelements.io
=> Adds the web-components keyword

.travis.yml, package.json
This uses node latest for our build
=> chore: use stable node for testing

package.json
=> chore: update saucelabs launchers

README.md
Add missing comma to code example.
=> Add missing comma to 0.12.x doc

src/defaults.js, src/lifecycle/created.js, src/lifecycle/resolve.js, test/lib/resolved.js, test/unit/attributes.js, test/unit/lifecycle.js, test/unit/lifecycle/render.js
=> #508 - Rename resolved to defined and add flag for rendered.

CHANGELOG.md, README.md, src/api/factory.js, src/api/skate.js, src/index.js, test/unit.js, test/unit/api/factory.js, test/unit/index.js
Implements #517. Already merged into #541.
=> #517 - Add factory function

CHANGELOG.md, README.md, src/lifecycle/events.js, test/unit/lifecycle/created.js, test/unit/lifecycle/events.js, test/unit/multiple-versions.js
=> #477 - Make event handler callbacks consistent with lifecycle callbacks.

package.json, src/api/skate.js, src/api/vdom.js, src/data.js, test/unit/vdom/incremental-dom.js
=> #565 and #566  - Fix iDOM props setter and clean up how props are set

README.md, src/api/prop.js, src/index.js, test/unit/api/properties.js
=> feat: number prop now defaults to zero

.travis.yml, README.md, karma.conf.js, src/api/vdom.js, src/lifecycle/render.js, test/unit/vdom/incremental-dom.js
Implements #638. This also references https://github.com/google/incremental-dom/issues/281 as referenced in the issue for this. It would be better if we could have built-in support for "components" as described in the [babel-plugin-incremental-dom docs](https://github.com/jridgewell/babel-plugin-incremental-dom#components).
=> #638 - Move special VDOM behaviour into Incremental DOM overrides.

src/lifecycle/events.js, test/unit/lifecycle/events.js
=> #650 - Fix illegal invocation error when matching event delegates

package.json, src/api/vdom.js, src/lifecycle/props-init.js, src/util/debounce.js, test/boot.js, test/unit/vdom/properties.js
=> #649 - Fix issue causing re-renders to fail when going from true to false with boolean props

package.json
=> 1.0.0-beta.8

karma.conf.js, package.json, rollup.config.js, src/api/component.js, src/api/define.js, src/api/state.js, src/api/symbols.js, src/api/vdom.js, src/lifecycle/props-init.js, src/lifecycle/render.js, src/util/define-property-constructor.js, src/util/support.js, src/util/symbols.js, test/boot.js, test/unit.js, test/unit/extending.js, test/unit/index.js, test/unit/lifecycle/events.js, test/unit/util/define-property-constructor.js, test/unit/vdom/elements.js, test/unit/vdom/events.js, test/unit/vdom/incremental-dom.js, test/unit/vdom/properties.js, test/unit/vdom/shadow-dom.js
I removed the v1 polyfill as I'd prefer to test in the more common, stable polyfill and create an
issue for testing with both polyfills separately.
Fixes #652.
=> #652 - Test with the stable v0 custom element polyfill and fix tests in it

src/api/vdom.js, test/unit/vdom/incremental-dom.js
=> #671 - Fix elementVoid() when passed function helpers

src/api/define.js, test/unit/api/define.js
fixed registerUniqueName and added a few tests to prove the fix
=> fixed registerUniqueName and added a few tests

README.md, src/api/component.js, test/unit/lifecycle/defined.js, test/unit/vdom/incremental-dom.js
=> feat: Add the "defined" attribute when the element is upgraded.

karma.conf.js, rollup.config.js, src/api/vdom.js, test/unit.js, test/unit/api/define.js, test/unit/lifecycle/attribute-changed.js, test/unit/vdom/elements.js, test/unit/vdom/ref.js, test/unit/vdom/skip.js
Issue #730 solved.
Some unrelated linting fixes.
=> Numbers as text

src/api/vdom.js, src/util/prop-context.js, test/unit/util/prop-context.js
=> fix: play nice with other libraries touching the idom.attributes global

package.json, src/api/emit.js
Also added test-watch script to make local testing with IE easier.
This fixes the IE failures introduced by #767
=> Make sure composed change is compatible with IE. 

README.md, src/api/emit.js
=> Add docs for ES2015 classes.

src/api/component.js, test/unit/api/component.js
I had to skip the precommit hook because it just wasnt letting me commit. 
All the linting passes but it still complains about extraneous packages (even after pruning...)
I figured CI would pick up on any *actual* issues
=> Fixes #820 updated Component.updated function to check for Symbols

README.md
15 minutes of my life lost in build debugging.
=> README: Add missing return in first example

package.json, rollup.config.js, src/api/component.js, src/api/define.js, src/api/emit.js, src/api/vdom.js, src/util/debounce.js, yarn.lock
It shouldn't fail to import / require() even though it may not be able to create custom elements.
fixes #893
=> fix: Fix issue causing the importing of Skate into Node to fail.

karma.browsers.js, package.json, src/api/emit.js, src/api/vdom.js, test/unit/vdom/events.js, yarn.lock
Simplified event handling code and updated tests to be more clear.
fixes #901
=> fix: Fix issues integrating with the polymer / webcomponents polyfills.

README.md
=> Revise note about symbol-keyed properties

src/index.d.ts
Callbacks added to **Component** type definition.
Fixes #940
=> #940 - Typings for component has been added

src/api/component.js
This fixes Firefox and Safari.
May also help with IE too.
=> (fix:with polyfill) fixes Firefox and Safari

README.md, src/api/component.js, src/index.d.ts, src/util/isType.js
=> refactor(component): Small code cleanup

src/api/component.js, test/unit/deprecated/lifecycle.js
=> #959 - Fix missing legacy lifecycle callbacks

README.md
@treshugart pls also add the link in repo About, I don't have edit rights
=> docs(Readme): add references to gitbook

docs/intro/README.md
=> docs: Add link to zzarcon's recent post to the resources section.

README.md
Raised #992 to create an API way to easily work around it.
=> #988 - document way to get around native class issue

src/api/prop.js, test/unit/api/properties.js
=> Add 'object' to built-in props

src/index.d.ts, test/definitions/misc.tsx
- adds `prop.object`
- makes `prop.object` and `prop.array` generic for better type inference
- adds new object type of `attribute` within prop definition
=> Update ts-typings to match latest API additions

book.json, package.json
plugins additions: 
in action:
=> chore(gitbook): tweak demos and add plugins

.gitignore, src/ts-typings/api.d.ts, test/definitions/misc.tsx, test/definitions/sample-component.tsx, tsconfig.json
=> fix(ts-typings): make prop api generic and 100% type safe

src/ts-typings/api.d.ts, test/definitions/sample-component.tsx
=> fix(ts-typings): allow renderCallback to pass props via args

src/ts-typings/api.d.ts, test/definitions/misc.tsx
=> fix(ts-typings): make define generic so it returns proper constructor

src/index.d.ts, src/ts-typings/api.d.ts, test/definitions/sample-component.tsx
=> fix(ts-typings): add missing api and fix LC hooks

src/util/index.js, src/util/with-props.js, src/with-props.js, src/with-unique.js, test/unit/util/index.spec.js, test/unit/with-props.spec.js
=> better debuggability by adding a description to sym

docs/recipes/design-patterns/component-composition.md
I guess so, otherwise I didn't understood how it works :)
=> docs(recipes): typo

nwb.config.js, package.json, yarn.lock
=> Add types back in

.gitignore, nwb.config.js, package.json
as we discussed here https://github.com/skatejs/project/pull/2#discussion_r117809028
=> build: add back es module + transpiled output

src/with-component.js, test/unit/with-render.spec.js
=> fix(render): Fix for #1196 Support progressive enhancement for components rendered with @skatejs/ssr

src/index.d.ts, src/ts-typings/api.d.ts
=> fix(render): Fix for #1199

src/index.js, src/with-children.js, src/with-component.js, src/with-props.js, src/with-renderer.js, src/with-unique.js, test/unit/index.spec.js, test/unit/with-children.spec.js
=> feat: Add childrenChangedCallback() mixin. Prettier'd some other files.

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, CONTRIBUTING.md, README.md, package.json, site/components/code.js, site/css/index.js, site/pages/index.js, site/pages/mixins/__samples__/with-children.js, site/pages/mixins/index.js, site/pages/renderers/with-preact.js, site/pages/renderers/with-react.js, site/utils/index.js, src/ts-types/types.d.ts, src/with-update.js, test/ts/mixins/with-children.tsx
*Why is this PR necessary?*
- lack of cross platform `code` styling
- wrong utils links
- update prettier + apply
- update markdown docs + contribution
=> docs: fix css and util links, update Readme, Contribution, prettier

README.md
- fix syntax error in example code
- fix format in example code
=> docs: fix example codes in README

.flowconfig, .github/ISSUE_TEMPLATE.md, README.md, packages/skatejs/src/emit.js
- Update docs to latest API's
- ignore site and tests from flow
- closes https://github.com/skatejs/skatejs/issues/1249
=> Docs tweaks

site/pages/migrating/index.js
fixes dead link in documentation
_Why have you implemented it this way? Did you try any other methods?_
_Are there any open questions about this implementation that need answers?_
_Is there anything else we should know? Delete this section if you don't need
it._
=> FIX dead link to lit-html renderer

site/pages/mixins/__samples__/with-update.js
I was looking at where to add [this detail](https://github.com/skatejs/skatejs/issues/1320#issuecomment-359957003) to the docs, but I'm a little confused by the first example. The update method returns a value, but it's not clear why anything needs to be returned.
Looking at with-update.js implementation, it doesn't do anything with a return value:
https://github.com/skatejs/skatejs/blob/master/packages/skatejs/src/with-update.js#L175
Maybe it's better to remove the return?
=> Remove return value from sample, it's not doing anything

site/pages/mixins/with-update.js
So people can better understand that updating instance props or attributes makes things automatically re-render.
=> Show how to update props on an instance

packages/ssr/register/index.js
So that we don't mess with APIs that can be used by end users.
_Why have you implemented it this way? Did you try any other methods?_
n/a
_Are there any open questions about this implementation that need answers?_
n/a
=> unpatch Object.defineProperty/ies after done using it

packages/skatejs/src/with-update.js
Fixes #1448. References #1452. cc @majo44 can you give this a quick thumbsup?
=> Fixes #1448

site/package.json
* [] Feature
previous sk-marked version is buggy. Fix travis
=> site: update sk-marked dependency

packages/skatejs/src/with-update.js
reopening of https://github.com/skatejs/skatejs/pull/1476 (see updated comments there)
See https://github.com/skatejs/skatejs/pull/1476
See https://github.com/skatejs/skatejs/pull/1476
=> fix: don't break observedAttributes of the base class
